### ISSUE TITLE
[Request] Settting the cursor color

### ISSUE THREAD

**Issue by thedjdoorn** [balazssagi/hyper-cat-cursor#1]
Love this project, great work bro!

It could be due to installed fonts et cetera, but I'm not getting an actual graphic, just the outline. That's okay, but in that case it would be nice to be able to change the color, since it's now just black, and hard to see on a black background.

**Comment by balazssagi** [comment]
Thanks for the suggestion! I'll look into it.

**Comment by rkmax** [comment]
dont work for me :/
