### ISSUE TITLE
Cursor disappear when enable this plugin

### ISSUE THREAD

**Issue by rkmax** [balazssagi/hyper-cat-cursor#3]

**Comment by karanwadhwa** [comment]
os: windows
shell: zsh 
after adding hyper-cat-cursor to plugins and catCursor object to config, the cursor disappears altogether.

**Comment by benc-uk** [comment]
Same here. Windows and zsh = no cursor 
no cats :(

**Comment by chenshuiluke** [comment]
I'm on Windows, with the default shell and there are no cats :(

**Comment by chenshuiluke** [comment]
![capture](https://user-images.githubusercontent.com/7980284/41192128-14aa6346-6bbf-11e8-86ea-2df87577be5c.PNG)
Not sure if this is related

**Comment by bahaa96** [comment]
I'm on mac and getting the same error message

**Comment by janjur** [comment]
Come on! This is important!

**Comment by gionkunz** [comment]
Please, I can't do my very important work because of this open issue!

**Comment by balazssagi** [comment]
The plugin is not compatible with Hyper 2.x 😿
