### ISSUE TITLE
hyper-cat-cursor does not take effect

### ISSUE THREAD

**Issue by a-marionette** [balazssagi/hyper-cat-cursor#4]
os: MacOS High Sierra
shell: bash
hyper: Canary 2.1.0
issue: Hyper-cat-cursor does not appear to take effect when enabling plugin. I have also tried adding the configuration parameters in the documentation

[hyper.txt](https://github.com/balazssagi/hyper-cat-cursor/files/2139834/hyper.txt)

**Comment by VioletIzHere** [comment]
I'm having the same issue. I installed hyper-cat-cursor but even after changing the configuration parameters, it had no effect.

Operating System: MacOS Mojave
Hyper Version: v2.0.0

**Comment by JessicaSachs** [comment]
Yeah. Same.

**Comment by balazssagi** [comment]
The plugin is not compatible with Hyper 2.x 😿
